spring:
  profiles:
    active: nl
jr:
  gebruikersnaam: Jeffrey
  wachtwoord: eenwachtwoord
  dburl: kukukechu
  jms:
    gebruikersnaam: GebruikerJMS
    wachtwoord: eenanderwachtwoord
    dburl: nanananananana

---
spring:
  profiles: nl
jr:
  jms:
    gebruikersnaam: Ajax